# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2021 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

---
- project:
    name: cloud-init-integration-pytest
    release:
      - bionic:
          release-is-lts: true
      - focal:
          release-is-lts: true
      - impish
      - jammy:
          release-is-lts: true
    platform:
      - lxd_container
      - lxd_vm
      - ec2
      - azure
      - gce
      - oci:
          platform-lts-only: true
    source:
      - daily-ppa
      - proposed
    exclude:
      - release-is-lts: false
        platform-lts-only: true
      - release: jammy
        platform: oci
    jobs:
      - cloud-init-integration-{platform}-{release}-{source}

- builder:
    name: cloud-init-integration-get-source-from-daily-ppa
    builders:
      - shell: |
          #!/bin/bash

          set -eux -o pipefail

          pull-ppa-source --ppa=cloud-init-dev/daily --no-verify-signature cloud-init {release}
          ln -s cloud-init-*/ cloud-init

- builder:
    name: cloud-init-integration-get-source-from-proposed
    builders:
      - shell: |
          #!/bin/bash

          set -eux -o pipefail

          # When pulling from the archive pull-pkg will fetch from
          # -proposed if the package is available there, otherwise
          # -release will be used.

          pull-lp-source cloud-init {release}
          ln -s cloud-init-*/ cloud-init

- job-template:
    name: cloud-init-integration-{platform}-{release}-{source}
    defaults: cloud-init
    triggers:
      - timed: !j2: "{{ {'git': '@daily', 'daily-ppa': '@weekly'}.get(source, '') }}"
    wrappers:
      - workspace-cleanup
      - timestamps
      - timeout:
          timeout: 180
          fail: true
      - credentials-binding:
          - file:
              credential-id: cloud-init-pycloudlib-config
              variable: PYCLOUDLIB_CONFIG
    publishers:
      - cloud-init-archive-integration-logs
    builders:
      - cloud-init-integration-get-source-from-{source}:
          release: '{release}'
      - shell: |
          #!/bin/bash

          set -eux -o pipefail

          export https_proxy=http://squid.internal:3128
          export no_proxy=launchpad.net,ubuntu.com,canonical.com,microsoftonline.com

          export CLOUD_INIT_PLATFORM={platform}
          export CLOUD_INIT_OS_IMAGE={release}
          export CLOUD_INIT_COLLECT_LOGS=ON_ERROR
          export CLOUD_INIT_LOCAL_LOG_PATH="$WORKSPACE/cloud_init_test_logs"
          export CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily

          if [[ {source} == proposed ]]; then
            CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED
          fi

          cd cloud-init
          tox -e integration-tests-jenkins -- -v --showlocals tests/integration_tests

- publisher:
    name: cloud-init-archive-integration-logs
    publishers:
      - archive:
          artifacts: 'cloud_init_test_logs'
          allow-empty: true
