---
name: ci

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-20.04
    steps:
      - name: Synchronize the package index (apt update)
        run: sudo apt-get -qy update
      - name: Install dependencies
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qy install tox
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run tox
        run: tox
